/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControllerFactura;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author 1001489.joan23
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form vistaInicio
     */
    public VistaInicio() {
        initComponents();
        this.setTitle("Apliacion Almacen");
        this.pwd_login.setEchoChar((char)0);
        
        //this.setExtendedState(VistaInicio.MAXIMIZED_BOTH);
        this.menuBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menu_login = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        msg_error = new javax.swing.JLabel();
        pwd_login = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        btn_productos = new javax.swing.JMenuItem();
        btn_logout = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Escritorio.setBackground(new java.awt.Color(204, 255, 51));
        Escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menu_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menu_login.setAlignmentX(100);

        txt_username.setText("Usuario");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });

        btn_send.setBackground(new java.awt.Color(153, 153, 153));
        btn_send.setMnemonic('a');
        btn_send.setText("Acceder");
        btn_send.setToolTipText("");
        btn_send.setBorderPainted(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        msg_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pwd_login.setText("Contraseña");
        pwd_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwd_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwd_loginFocusLost(evt);
            }
        });
        pwd_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_loginActionPerformed(evt);
            }
        });
        pwd_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwd_loginKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/image/user (Custom).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);

        javax.swing.GroupLayout menu_loginLayout = new javax.swing.GroupLayout(menu_login);
        menu_login.setLayout(menu_loginLayout);
        menu_loginLayout.setHorizontalGroup(
            menu_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(menu_loginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(menu_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_username)
                    .addComponent(pwd_login)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_loginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)))
                .addGap(49, 49, 49))
        );
        menu_loginLayout.setVerticalGroup(
            menu_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_loginLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(msg_error, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwd_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        Escritorio.add(menu_login);
        menu_login.setBounds(350, 70, 340, 530);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Menu");

        btn_productos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        btn_productos.setMnemonic('o');
        btn_productos.setText("Productos");
        btn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productosActionPerformed(evt);
            }
        });
        fileMenu.add(btn_productos);

        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        fileMenu.add(btn_logout);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productosActionPerformed
        // TODO add your handling code here:

        VistaProducto vistaproducto = new VistaProducto();
        
        this.Escritorio.add(vistaproducto);

        vistaproducto.toFront();

        vistaproducto.setVisible(true);
        
        
        
        

    }//GEN-LAST:event_btn_productosActionPerformed
public void login(){
    this.msg_error.setText("");
        int error_login = 0;
        if (this.txt_username.getText().equals("Usuario")){
            this.msg_error.setText("Introduce un usuario");
            error_login = 1;
        } else if(this.pwd_login.getText().equals("Contraseña")){
            this.msg_error.setText("Introduce una contraseña");
            error_login = 1;
        }else{
        
        //llamar a la funcion de login
    
                // Obtener el password

        char passArray[] = pwd_login.getPassword();

        // Revisar que sean letras y numeros
        String pass = "";
        for (int i = 0; i < passArray.length; i++) {

            char c = passArray[i];

            // Si no es letra o numero entonces no es valido

            pass = pass + c ;

        }
       
        
       String usuario = this.txt_username.getText();
       
        ControllerFactura inicio = new ControllerFactura();
       boolean login = inicio.login(usuario, pass);
       
        if(login){
            error_login = 1;
            
        }else{
            error_login =0;
        }
        
        
        if (error_login == 0){
            this.msg_error.setText("Usuario o contraseña incorrectos");
        }else{
            this.menu_login.setVisible(false);
            
            VistaProducto vistaproducto = new VistaProducto();
        
        this.Escritorio.add(vistaproducto);

        vistaproducto.toFront();

        vistaproducto.setVisible(true);
        this.menuBar.setVisible(true);
        }
        //this.msg_error.setVisible(true);
        }
}
    
    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btn_sendActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        // TODO add your handling code here:
        if (this.txt_username.getText().equals("Usuario")){
                this.txt_username.setText("");
        }
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        
        if (this.txt_username.getText().equals("")){
            this.txt_username.setText("Usuario");
        }

    }//GEN-LAST:event_txt_usernameFocusLost

    private void pwd_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_loginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pwd_loginActionPerformed

    private void pwd_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_loginFocusGained

        if (this.pwd_login.getText().equals("Contraseña")){
                this.pwd_login.setText("");
                this.pwd_login.setEchoChar('*');
        }
                
    }//GEN-LAST:event_pwd_loginFocusGained

    private void pwd_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_loginFocusLost
        // TODO add your handling code here:
        if (this.pwd_login.getText().equals("")){
        this.pwd_login.setEchoChar((char)0);
        this.pwd_login.setText("Contraseña");
        }
        
    }//GEN-LAST:event_pwd_loginFocusLost

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
        //Your Code
        login();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void pwd_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_loginKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
        //Your Code
        login();
        }
    }//GEN-LAST:event_pwd_loginKeyPressed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        String nl = System.getProperty("line.separator");
  //Lanzamos el mensaje:
    JOptionPane.showMessageDialog(null, "Programa de gestión de almacenes"
    + nl + ""
    + nl + "Marc Petit e Israel Perea");
        
        
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        this.menu_login.setVisible(true);
            
            VistaProducto vistaproducto = new VistaProducto();
        
        

        vistaproducto.setVisible(false);
        this.menuBar.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem btn_logout;
    private javax.swing.JMenuItem btn_productos;
    private javax.swing.JButton btn_send;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menu_login;
    private javax.swing.JLabel msg_error;
    private javax.swing.JPasswordField pwd_login;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
